"use strict";
var fs = require("fs");
var path = require("path");
var flowUtils = require("../../../../FlowHelpers/1.0.0/interfaces/flowUtils");

var normalizeInputs = function (inputs) {
    if (Array.isArray(inputs)) {
        return inputs;
    }
    if (inputs && typeof inputs === "object") {
        return Object.keys(inputs).map(function (key) { return ({ name: key, value: inputs[key] }); });
    }
    return [];
};

var getInputValue = function (inputs, name, fallback) {
    var input = inputs.find(function (i) { return i.name === name; });
    if (!input || typeof input.value === "undefined") {
        return fallback;
    }
    return input.value;
};

var details = function () { return ({
    name: "Subtitles: Import from Manifest",
    description:
        "Reads a _subtitles.exports manifest file (generated by Extract Subtitles PgsToSrtPlus) " +
        "and adds the extracted SRT files as additional subtitle streams for the ffmpeg remux. " +
        "Respects the preferTextDefault flag to reassign the default disposition.",
    style: {
        borderColor: "purple",
    },
    tags: "subtitle",
    isStartPlugin: false,
    pType: "",
    requiresVersion: "2.11.01",
    sidebarPosition: 6,
    icon: "faClosedCaptioning",
    inputs: [
        {
            name: "Manifest Directory",
            type: "string",
            defaultValue: "",
            inputUI: "directory",
            tooltip:
                "Directory where the _subtitles.exports manifest and SRT files are located. " +
                "Leave empty to auto-detect from the Tdarr cache/work directory. " +
                "Supports {{{args.variables...}}} placeholders.",
        },
        {
            name: "Prefer Text Subtitle as Default",
            type: "string",
            defaultValue: "false",
            inputUI: "switch",
            tooltip:
                "When enabled, if the manifest indicates preferTextDefault was used during extraction, " +
                "the default disposition will be assigned to the first non-commentary text subtitle " +
                "rather than an image-based (OCR'd) subtitle. " +
                "This should match the setting used in the extraction plugin.",
        },
    ],
    outputs: [
        {
            number: 1,
            tooltip: "Continue to next plugin",
        },
    ],
}); };
exports.details = details;

// Manifest line format:
// file|index|lang|codec|delay|forced|title|hearing_impaired|visual_impaired|default|comment
var parseManifestLine = function (line) {
    var parts = line.split("|");
    if (parts.length < 11) return null;
    return {
        file: parts[0],
        index: parseInt(parts[1], 10),
        lang: parts[2],
        codec: parts[3],
        delay: parseFloat(parts[4]) || 0,
        forced: parseInt(parts[5], 10) || 0,
        title: parts[6] || "",
        hearingImpaired: parseInt(parts[7], 10) || 0,
        visualImpaired: parseInt(parts[8], 10) || 0,
        isDefault: parseInt(parts[9], 10) || 0,
        isComment: parseInt(parts[10], 10) || 0,
    };
};

var resolveInput = function (value, args) {
    if (typeof value !== "string") return value;
    var match = value.match(/^\{\{\{\s*(.+?)\s*\}\}\}$/);
    if (!match) return value;
    var expr = match[1].trim();
    try {
        var fn = new Function("args", "return " + expr + ";");
        var resolved = fn(args);
        if (resolved !== undefined && resolved !== null) return resolved;
    } catch (err) {
        // ignore
    }
    return "";
};

var plugin = function (args) { return (function () {
    var lib = require("../../../../../methods/lib")();
    var inputs = lib.loadDefaultValues(normalizeInputs(args.inputs), details);
    args.inputs = inputs;
    flowUtils.checkFfmpegCommandInit(args);

    var manifestDirRaw = (getInputValue(inputs, "Manifest Directory", "") || "").toString().trim();
    var manifestDir = resolveInput(manifestDirRaw, args) || "";
    var preferTextDefault = String(getInputValue(inputs, "Prefer Text Subtitle as Default", "false")) === "true";

    // Determine the base name from the input file
    var inputPath = args.inputFileObj._id || args.inputFileObj.file || "";
    var baseName = path.basename(inputPath, path.extname(inputPath));

    // Search for the manifest file in likely locations
    var candidateDirs = [];
    if (manifestDir) {
        candidateDirs.push(manifestDir);
    }
    if (args.workDir) {
        candidateDirs.push(args.workDir);
    }
    if (args.librarySettings && args.librarySettings.cache) {
        candidateDirs.push(args.librarySettings.cache);
    }
    // Also check the directory of the input file itself
    candidateDirs.push(path.dirname(inputPath));

    var manifestFile = baseName + "_subtitles.exports";
    var manifestPath = null;

    for (var i = 0; i < candidateDirs.length; i++) {
        var candidate = path.join(candidateDirs[i], manifestFile);
        if (fs.existsSync(candidate)) {
            manifestPath = candidate;
            break;
        }
    }

    if (!manifestPath) {
        args.jobLog("No subtitle manifest found (" + manifestFile + "); skipping import.");
        return {
            outputFileObj: args.inputFileObj,
            outputNumber: 1,
            variables: args.variables,
        };
    }

    args.jobLog("Found subtitle manifest: " + manifestPath);
    var manifestContent = fs.readFileSync(manifestPath, "utf8").trim();
    if (!manifestContent) {
        args.jobLog("Manifest file is empty; skipping import.");
        return {
            outputFileObj: args.inputFileObj,
            outputNumber: 1,
            variables: args.variables,
        };
    }

    var lines = manifestContent.split("\n").filter(function (l) { return l.trim().length > 0; });
    var entries = [];
    for (var i = 0; i < lines.length; i++) {
        var entry = parseManifestLine(lines[i].trim());
        if (entry) {
            entries.push(entry);
        } else {
            args.jobLog("Skipping malformed manifest line: " + lines[i]);
        }
    }

    if (entries.length === 0) {
        args.jobLog("No valid entries in manifest; skipping import.");
        return {
            outputFileObj: args.inputFileObj,
            outputNumber: 1,
            variables: args.variables,
        };
    }

    args.jobLog("Importing " + entries.length + " subtitle stream(s) from manifest.");

    var manifestBaseDir = path.dirname(manifestPath);
    var additionalInputs = args.variables.ffmpegCommand.additionalInputs || [];
    var tempFiles = args.variables.ffmpegCommand.tempFiles || [];
    var streams = args.variables.ffmpegCommand.streams || [];

    // Remove existing subtitle streams from the ffmpegCommand streams — the
    // manifest is the authoritative source for subtitles after extraction.
    var nonSubStreams = streams.filter(function (s) { return s.codec_type !== "subtitle"; });

    // Start input index after main input (0) plus any existing additional inputs
    var inputIdx = additionalInputs.length + 1;
    var newSubStreams = [];

    // If preferTextDefault is enabled, apply the default logic across manifest entries.
    // The extraction plugin already ordered entries with the default first and set
    // isDefault flags, but we re-evaluate here in case the user wants to override.
    if (preferTextDefault) {
        // Check if the current default is on an image-based (OCR'd) entry
        var hasImageDefault = entries.some(function (e) { return e.isDefault && e.isComment === 0; }) &&
            entries.some(function (e) {
                return e.isDefault &&
                    // OCR'd entries come from PGS extraction — they won't have isImageBased
                    // in the manifest directly, but we can check codec. If the codec is
                    // pgs/hdmv, it was image-based. However, extracted SRTs from PGS will
                    // have codec "subrip" or similar. The extraction plugin marks isImageBased
                    // but the manifest format doesn't include that directly...
                    // Actually, looking at the manifest format more carefully: the codec field
                    // stores the ORIGINAL codec. So PGS-extracted entries will have codec
                    // "hdmv_pgs_subtitle" or similar, even though the output is SRT.
                    (e.codec || "").toLowerCase().includes("pgs") ||
                    (e.codec || "").toLowerCase().includes("hdmv");
            });

        if (hasImageDefault) {
            // Find the first non-commentary, non-image-based text subtitle
            var defaultLang = "";
            for (var i = 0; i < entries.length; i++) {
                if (entries[i].isDefault) {
                    defaultLang = entries[i].lang;
                    break;
                }
            }

            var candidateIdx = -1;
            // First try same language
            for (var i = 0; i < entries.length; i++) {
                var codec = (entries[i].codec || "").toLowerCase();
                var isImageCodec = codec.includes("pgs") || codec.includes("hdmv");
                if (!isImageCodec && !entries[i].isComment && entries[i].lang === defaultLang) {
                    candidateIdx = i;
                    break;
                }
            }
            // Fallback to any language
            if (candidateIdx === -1) {
                for (var i = 0; i < entries.length; i++) {
                    var codec = (entries[i].codec || "").toLowerCase();
                    var isImageCodec = codec.includes("pgs") || codec.includes("hdmv");
                    if (!isImageCodec && !entries[i].isComment) {
                        candidateIdx = i;
                        break;
                    }
                }
            }

            if (candidateIdx !== -1) {
                // Clear all defaults, set the candidate
                for (var i = 0; i < entries.length; i++) {
                    entries[i].isDefault = 0;
                }
                entries[candidateIdx].isDefault = 1;
                args.jobLog("preferTextDefault: reassigned default to " + entries[candidateIdx].file);
            }
        }
    }

    for (var i = 0; i < entries.length; i++) {
        var entry = entries[i];
        var srtPath = path.join(manifestBaseDir, entry.file);

        if (!fs.existsSync(srtPath)) {
            args.jobLog("Warning: SRT file not found, skipping: " + srtPath);
            continue;
        }

        additionalInputs.push(srtPath);
        tempFiles.push(srtPath);

        var mapArgs = ["-map", inputIdx + ":s:0?"];
        var outputArgs = [
            "-c:s", "srt",
            "-metadata:s:s:{outputTypeIndex}", "language=" + entry.lang,
        ];

        if (entry.title) {
            outputArgs.push("-metadata:s:s:{outputTypeIndex}");
            outputArgs.push("title=" + entry.title);
        }

        // Set dispositions
        var dispositions = [];
        if (entry.isDefault) dispositions.push("default");
        if (entry.forced) dispositions.push("forced");
        if (entry.hearingImpaired) dispositions.push("hearing_impaired");
        if (entry.visualImpaired) dispositions.push("visual_impaired");
        if (entry.isComment) dispositions.push("comment");

        if (dispositions.length > 0) {
            outputArgs.push("-disposition:s:{outputTypeIndex}");
            outputArgs.push(dispositions.join("+"));
        } else {
            // Explicitly clear dispositions to avoid inheriting from source
            outputArgs.push("-disposition:s:{outputTypeIndex}");
            outputArgs.push("0");
        }

        newSubStreams.push({
            index: inputIdx,
            codec_type: "subtitle",
            mapArgs: mapArgs,
            outputArgs: outputArgs,
            inputArgs: [],
            removed: false,
            language: entry.lang,
        });

        args.jobLog("  Added: " + entry.file + " [" + entry.lang + "]" +
            (entry.isDefault ? " (default)" : "") +
            (entry.forced ? " (forced)" : "") +
            (entry.isComment ? " (commentary)" : ""));

        inputIdx++;
    }

    if (newSubStreams.length === 0) {
        args.jobLog("No SRT files found on disk; skipping import.");
        return {
            outputFileObj: args.inputFileObj,
            outputNumber: 1,
            variables: args.variables,
        };
    }

    // Register the manifest file itself for cleanup after remux
    tempFiles.push(manifestPath);

    args.variables.ffmpegCommand.streams = nonSubStreams.concat(newSubStreams);
    args.variables.ffmpegCommand.additionalInputs = additionalInputs;
    args.variables.ffmpegCommand.tempFiles = tempFiles;
    args.variables.ffmpegCommand.shouldProcess = true;
    args.variables.ffmpegCommand.init = true;

    args.jobLog("Subtitle import complete: " + newSubStreams.length + " stream(s) added.");

    return {
        outputFileObj: args.inputFileObj,
        outputNumber: 1,
        variables: args.variables,
    };
})(); };
exports.plugin = plugin;
